plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    alias(libs.plugins.ksp)
}

android {
    defaultConfig {
        applicationId "com.udharpay"
        minSdkVersion 24
        compileSdk 35
        targetSdkVersion 35
        versionCode 1
        versionName "1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    sourceSets {
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            manifestPlaceholders.providerName = "com.udharpay.sdk"
            buildConfigField "String", "PROVIDER_NAME", "\"com.udharpay.sdk.provider\""

            applicationIdSuffix = '.sdk'

            //Whitelabel
//            buildConfigField("String", "ENTERPRISE_ID", "\"00000198-bd64-6c3a-b857-49bc88b0ed9b\"")
//            buildConfigField("String", "ENTERPRISE_TOKEN", "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwMTk4LWUxNzYtNjYwMi05ZGIxLWJkMTkxNjUyMDI2YyIsIm1vYmlsZV9udW1iZXIiOiIrOTE5NDAzMzgyNDIyIiwibWVyY2hhbnRfaWQiOiIwMDAwMDE5OS0zNDAzLTg0ZDUtYmM0My00OTgzZGM2OTgxNGUiLCJyb2xlIjoiQURNSU4iLCJhY2NvdW50X3R5cGUiOiJFTlRFUlBSSVNFIiwic291cmNlIjoiQ09NTU9OX0xPR0lOIiwiaWF0IjoxNzU3NTE4NTEzfQ.Hd0E6y146AoBW-oL4ul_K2s9mrWaTCSAHzOj-coXZS0\"")

            //EMI Safe
            buildConfigField("String", "ENTERPRISE_ID", "\"00000199-38cd-230d-8d1b-30a57e344467\"")
            buildConfigField("String", "ENTERPRISE_TOKEN", "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwMTk4LWUxNzYtNjYwMi05ZGIxLWJkMTkxNjUyMDI2YyIsIm1vYmlsZV9udW1iZXIiOiIrOTE5NDAzMzgyNDIyIiwibWVyY2hhbnRfaWQiOiIwMDAwMDE5OS0zOGNkLTIzMGQtOGQxYi0zMGE1N2UzNDQ0NjciLCJyb2xlIjoiRElTVFJJQlVUT1JfQURNSU4iLCJhY2NvdW50X3R5cGUiOiJESVNUUklCVVRPUiIsInNvdXJjZSI6IkNPTU1PTl9MT0dJTiIsImVudGVycHJpc2VfaWQiOiIwMDAwMDE5OS0zOGNkLTIzMGQtOGQxYi0zMGE1N2UzNDQ0NjciLCJpYXQiOjE3NTc2NzQ2NTF9.okrd59KVYYiN5zQAz1naBoqPeisv1_p3uDpRyES2Bts\"")

        }

        debug {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            manifestPlaceholders.providerName = "com.udharpay.sdk.debug"
            buildConfigField "String", "PROVIDER_NAME", "\"com.udharpay.sdk.debug.provider\""

            applicationIdSuffix = '.sdk.debug'

            //Whitelabel
//            buildConfigField("String", "ENTERPRISE_ID", "\"00000198-bd64-6c3a-b857-49bc88b0ed9b\"")
//            buildConfigField("String", "ENTERPRISE_TOKEN", "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwMTk4LWUxNzYtNjYwMi05ZGIxLWJkMTkxNjUyMDI2YyIsIm1vYmlsZV9udW1iZXIiOiIrOTE5NDAzMzgyNDIyIiwibWVyY2hhbnRfaWQiOiIwMDAwMDE5OS0zNDAzLTg0ZDUtYmM0My00OTgzZGM2OTgxNGUiLCJyb2xlIjoiQURNSU4iLCJhY2NvdW50X3R5cGUiOiJFTlRFUlBSSVNFIiwic291cmNlIjoiQ09NTU9OX0xPR0lOIiwiaWF0IjoxNzU3NTE4NTEzfQ.Hd0E6y146AoBW-oL4ul_K2s9mrWaTCSAHzOj-coXZS0\"")

            //EMI Safe
            buildConfigField("String", "ENTERPRISE_ID", "\"00000199-38cd-230d-8d1b-30a57e344467\"")
            buildConfigField("String", "ENTERPRISE_TOKEN", "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwMTk4LWUxNzYtNjYwMi05ZGIxLWJkMTkxNjUyMDI2YyIsIm1vYmlsZV9udW1iZXIiOiIrOTE5NDAzMzgyNDIyIiwibWVyY2hhbnRfaWQiOiIwMDAwMDE5OS0zOGNkLTIzMGQtOGQxYi0zMGE1N2UzNDQ0NjciLCJyb2xlIjoiRElTVFJJQlVUT1JfQURNSU4iLCJhY2NvdW50X3R5cGUiOiJESVNUUklCVVRPUiIsInNvdXJjZSI6IkNPTU1PTl9MT0dJTiIsImVudGVycHJpc2VfaWQiOiIwMDAwMDE5OS0zOGNkLTIzMGQtOGQxYi0zMGE1N2UzNDQ0NjciLCJpYXQiOjE3NTc2NzQ2NTF9.okrd59KVYYiN5zQAz1naBoqPeisv1_p3uDpRyES2Bts\"")

        }
    }

    buildFeatures {
        dataBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
    namespace 'com.udharpay'
}

dependencies {

    // Multi dex support for android version < 21
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation "androidx.activity:activity:1.10.1"
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation project(':mandate-module')

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.1'
    androidTestImplementation 'androidx.test:rules:1.6.1'

}

