[versions]
agp = "8.8.2"
core = "3.5.3"
dagger = "2.49"
glide = "4.12.0"
gson = "2.10.1"
kotlin = "2.1.0"
ksp = "2.0.20-1.0.25"
chucker-library = "4.2.0"
lifecycleRuntimeKtx = "2.8.3"
lifecycleViewmodelKtx = "2.8.3"
playServicesAdsIdentifier = "18.1.0"
playServicesAuth = "21.2.0"
playServicesAuthApiPhone = "18.1.0"
playServicesLocation = "21.3.0"
retrofit = "2.9.0"
room = "2.6.1"
junitVersion = "1.1.5"
espressoCore = "3.5.0"
shimmer = "0.5.0"
coreKtx = "1.16.0"
junit = "4.13.2"
appcompat = "1.7.1"
material = "1.12.0"
swiperefreshlayout = "1.1.0"
workRuntimeKtx = "2.9.0"

[libraries]
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
core = { module = "com.google.zxing:core", version.ref = "core" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gms-play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

chucker-library = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker-library" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-auth-api-phone = { module = "com.google.android.gms:play-services-auth-api-phone", version.ref = "playServicesAuthApiPhone" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
