package com.rocketpay.mandate.feature.business.domain.usecase

import com.rocketpay.mandate.common.jsonconverter.JsonConverter
import com.rocketpay.mandate.feature.business.domain.entities.BusinessInfoConfig

internal class BusinessProfileUseCase {

    fun getBusinessProfileConfig(): BusinessInfoConfig? {
        val businessFieldValuesString = "{\"fields\":[{\"title\":\"Business type\",\"hint\":\"Select your business type\",\"subtitle\":\"We need it for creating your profile\",\"primary_text\":\"Complete\",\"type\":\"business_type\",\"priority\":1,\"type_values\":[{\"priority\":0,\"title\":\"Wholesaler\",\"type\":\"wholesaler\",\"value\":\"wholesaler\"},{\"priority\":1,\"title\":\"Distributor\",\"type\":\"distributor\",\"value\":\"distributor\"},{\"priority\":2,\"title\":\"Retailer\",\"type\":\"retailer\",\"value\":\"retailer\"},{\"priority\":3,\"title\":\"Manufacturer\",\"type\":\"manufacturer\",\"value\":\"manufacturer\"},{\"priority\":4,\"title\":\"I dont have a business or shop\",\"type\":\"no\",\"value\":\"\"},{\"priority\":5,\"title\":\"Other business or shop\",\"type\":\"other\",\"value\":\"\",\"type_meta\":{\"hint\":\"Enter your business type\",\"regex\":\"[A-Za-z][A-Za-z0-9 !@#&'-,]{2,32}\",\"error\":\"Please enter valid business type\"}}]},{\"title\":\"Business category\",\"hint\":\"Select your business category\",\"subtitle\":\"We need it for creating your profile\",\"primary_text\":\"Complete\",\"type\":\"business_category\",\"priority\":2,\"type_values\":[{\"priority\":0,\"title\":\"Electronics or mobile\",\"type\":\"electronics_mobile\",\"value\":\"electronics_mobile\"},{\"priority\":1,\"title\":\"Finance or lending business\",\"type\":\"finance_or_lending\",\"value\":\"finance_or_lending\"},{\"priority\":2,\"title\":\"Hardware\",\"type\":\"hardware\",\"value\":\"hardware\"},{\"priority\":3,\"title\":\"Clothing or fashion\",\"type\":\"clothing_or_fashion\",\"value\":\"clothing_or_fashion\"},{\"priority\":4,\"title\":\"I dont have a business or shop\",\"type\":\"no\",\"value\":\"\"},{\"priority\":5,\"title\":\"Other business or shop\",\"type\":\"other\",\"value\":\"\",\"type_meta\":{\"hint\":\"Enter your business category\",\"regex\":\"[A-Za-z][A-Za-z0-9 !@#&'-,]{2,32}\",\"error\":\"Please enter valid business category\"}}]},{\"title\":\"Business name\",\"hint\":\"Enter Business or shop name\",\"subtitle\":\"This name will be shown to your customers\",\"primary_text\":\"Complete\",\"type\":\"business_name\",\"priority\":0,\"type_values\":[{\"priority\":0,\"title\":\"Business or shop name\",\"type\":\"business_name\",\"value\":\"\",\"type_meta\":{\"hint\":\"Business or shop name\",\"regex\":\"[A-Za-z][A-Za-z0-9 !@#&'-,]{2,32}\",\"error\":\"Please enter valid business or shop name\"}}],\"type_meta\":{\"hint\":\"Business or shop name\",\"regex\":\"[A-Za-z][A-Za-z0-9 !@#&'-,]{2,32}\",\"error\":\"Please enter valid business or shop name\"}}]}"
        return JsonConverter.getInstance().fromJson(businessFieldValuesString, BusinessInfoConfig::class.java)
    }
}